#!/bin/bash
cd $OPENSHIFT_DATA_DIR

if [ ! -d apache-maven-3.3.9 ]; then
  wget http://www.eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  tar -zxf apache-maven-3.3.9-bin.tar.gz
  rm -rf apache-maven-3.3.9-bin.tar.gz
fi

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

$OPENSHIFT_DATA_DIR/apache-maven-3.3.9/bin/mvn -f $OPENSHIFT_REPO_DIR/pom.xml clean package -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -DskipTests=true

#cd $OPENSHIFT_REPO_DIR
#mvn package -s .openshift/settings.xml -DskipTests=true
